apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-secret
  namespace: nextcloud
type: Opaque
stringData:
  username: nextcloud
  password: 21aztec5

---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-redis-secret
  namespace: nextcloud
type: Opaque
stringData:
  redis-password: 21aztec5
