apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: nextcloud-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway    # matches your istio-ingressgateway Service/Deployment label
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - nextcloud.ghosthacker.dev
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - nextcloud.ghosthacker.dev
      tls:
        mode: SIMPLE
        credentialName: nextcloud-tls   # Kubernetes TLS secret in istio-system
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  hosts:
    - nextcloud.ghosthacker.dev
  gateways:
    - istio-system/nextcloud-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: nextcloud.nextcloud.svc.cluster.local
            port:
              number: 80
      timeout: 600s
      retries:
        attempts: 3
        perTryTimeout: 30s
        retryOn: gateway-error,connect-failure,refused-stream
      headers:
        request:
          add:
            X-Forwarded-Proto: "https"
